### ISSUE TITLE
emeralds only spawn 1025 above ground

### ISSUE THREAD

**Issue by programmerjake** [runsy/juanchi#1]
I would expect emeralds to spawn underground, however, the `register_ore` call makes them spawn from 1025 to 31000 rather than the more usual -1025 to -31000:

https://github.com/runsy/juanchi/blob/3c331e0471156cbe9dcfe6a0502ad53c56d48803/mods/emeralds/emeralds.lua#L34-L43

**Comment by runsy** [comment]
Fixed.

**Comment by programmerjake** [comment]
Did you intend for emeralds to spawn at ground level? I would have picked something like -256 to -31000 instead of what it was changed to -- 31000 (above ground) to -1025.

I suggest changing it to:
```lua
minetest.register_ore({
    ore_type = "scatter",
    ore = "emeralds:emerald_ore",
    wherein = "default:stone",
    clust_scarcity = 12*12*12,
    clust_num_ores = 5,
    clust_size = 5,
    y_min = -31000,
    y_max = -256,
})
```

**Comment by runsy** [comment]
> ```lua
> minetest.register_ore({
>     ore_type = "scatter",
>     ore = "emeralds:emerald_ore",
>     wherein = "default:stone",
>     clust_scarcity = 12*12*12,
>     clust_num_ores = 5,
>     clust_size = 5,
>     y_min = -31000,
>     y_max = -256,
> })
> ```

You've right.
Fixed!
